# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1604"

  cli_path="github.com/eris-ltd/eris-cli"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git gcc apt-transport-https ca-certificates linux-image-extra-$(uname -r) linux-image-extra-virtual
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get install -y docker-engine
    usermod -aG docker vagrant
    service docker start
    newgrp -
    curl -s https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz | tar -C /usr/local -xz
    ln -s /usr/local/go/bin/* /usr/local/bin/
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    export GOPATH=$HOME/go
    echo "export GOPATH=$GOPATH" >> "$HOME/.profile"
    echo "export PATH=$GOPATH/bin:$PATH" >> "$HOME/.profile"
    mkdir -p $GOPATH
    source "$HOME/.profile"
    go get -d #{cli_path}
    cd $GOPATH/src/#{cli_path}
    git checkout release_0.12
    go install ./cmd/eris
    eris init
    docker pull tutum/logrotate
  SHELL
end
